name: DEBUG - Apicurio Registry Operate First E2E Tests
on:
  push:
  #   branches: [ main ]
  # schedule:
  #   - cron: "*/30 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Install dependencies
      run: npm ci

    # Caching Playwright from: https://github.com/microsoft/playwright/issues/7249
    # Doesn't work properly with Ubuntu + a specific browser to be identified
    - name: Get installed Playwright version
      id: playwright-version
      run: echo "version=$(npm ls @playwright/test | grep @playwright | sed 's/.*@//')" >> $GITHUB_OUTPUT
    - uses: actions/cache@v3
      id: playwright-cache
      with:
        path: '~/.cache/ms-playwright'
        key: '${{ runner.os }}-playwright-debug-cache-deps-${{ steps.playwright-version.outputs.version }}'
        restore-keys: |
          ${{ runner.os }}-playwright-debug-cache-deps-
    - name: Install Playwright's dependencies
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps chromium chrome msedge firefox webkit
    # End of caching
    # - name: Install Playwright's OS dependencies
    #   run: npx playwright install-deps

    - name: Run Playwright tests
      env:
        TEST_USERNAME: ${{ secrets.USERNAME }}
        TEST_PASSWORD: ${{ secrets.PASSWORD }}
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 1

    # Re-enable me on Monday
    # - name: Google Chat Notification
    #   uses: Co-qn/google-chat-notification@releases/v1
    #   with:
    #     name: Operate First E2E Test
    #     url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
    #     status: ${{ job.status }}
    #   if: failure()
