name: Full - Apicurio Registry Operate First E2E Tests
on:
  push:
    branches: [ main ]
#  schedule:
#    - cron: "*/30 * * * *"

concurrency:
  # Only run once this workflow
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  playwright:
    uses: andreaTP/apicurio-gh-workflows/.github/workflows/playwright.yaml@playwright
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    with:
      os: ${{ matrix.os }}
      notify-on-failure: true
    secrets:
      username: "${{ secrets.USERNAME }}-${{ matrix.os }}"
      password: ${{ secrets.PASSWORD }}
      chat-webhook: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
