name: Apicurio Registry Operate First E2E Tests
on:
  push:
  #   branches: [ main ]
  # schedule:
  #   - cron: "*/30 * * * *"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [macos-latest]
    continue-on-error: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Install dependencies
      run: npm ci

    - name: Install Playwright's dependencies
      run: npx playwright install --with-deps chromium chrome msedge firefox webkit

    - name: Run Playwright tests
      env:
        TEST_USERNAME: ${{ secrets.USERNAME }}
        TEST_PASSWORD: ${{ secrets.PASSWORD }}
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 10
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 10
