name: Quick - Apicurio Registry Operate First E2E Tests
on:
  push:
    branches: [ main ]

concurrency:
  # Only run once this workflow
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  playwright:
    uses: andreaTP/apicurio-gh-workflows/.github/workflows/playwright.yaml@playwright
    with:
      os: ubuntu-latest
      options: "--project chromium"
      notify-on-failure: false
    secrets:
      username: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}
